server:
  port: 8040
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/mcorder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    name: mcorder
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.mc.pojo